export enum ErrorCode {
  // Auth Errors
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_NOT_CONFIRMED = "AUTH_EMAIL_NOT_CONFIRMED",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  AUTH_USER_ALREADY_EXISTS = "AUTH_USER_ALREADY_EXISTS",
  AUTH_WEAK_PASSWORD = "AUTH_WEAK_PASSWORD",
  AUTH_INVALID_EMAIL = "AUTH_INVALID_EMAIL",
  AUTH_UNKNOWN = "AUTH_UNKNOWN",

  // Network/System Errors
  NETWORK_ERROR = "NETWORK_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",

  // Validation Errors
  INVALID_INPUT = "INVALID_INPUT",

  // Progress Photo Errors
  PROGRESS_MISSING_PUBLIC_KEY = "PROGRESS_MISSING_PUBLIC_KEY",
  PROGRESS_PARTNER_FETCH_ERROR = "PROGRESS_PARTNER_FETCH_ERROR",
  PROGRESS_ENCRYPTION_ERROR = "PROGRESS_ENCRYPTION_ERROR",
  PROGRESS_UPLOAD_ERROR = "PROGRESS_UPLOAD_ERROR",
  PROGRESS_DB_INSERT_ERROR = "PROGRESS_DB_INSERT_ERROR",
}

export interface AppError {
  code: ErrorCode;
  message: string;
  originalError?: any;
}
