export enum ErrorCode {
  // Auth Errors
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_NOT_CONFIRMED = "AUTH_EMAIL_NOT_CONFIRMED",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  AUTH_USER_ALREADY_EXISTS = "AUTH_USER_ALREADY_EXISTS",
  AUTH_WEAK_PASSWORD = "AUTH_WEAK_PASSWORD",
  AUTH_INVALID_EMAIL = "AUTH_INVALID_EMAIL",
  AUTH_UNKNOWN = "AUTH_UNKNOWN",

  // Network/System Errors
  NETWORK_ERROR = "NETWORK_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}

export interface AppError {
  code: ErrorCode;
  message: string;
  originalError?: any;
}
